version: '2'
services:
    sccindicadores-app:
        image: sccindicadores
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sccindicadores-mysql:3306/sccindicadores?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8084:8084
    sccindicadores-mysql:
        extends:
            file: mysql.yml
            service: sccindicadores-mysql
